version: '3.8'

services:

  api:
    build: .
    ports:
      - 8000:8000
    command: uvicorn main:app --host 0.0.0.0 --reload
    volumes:
      - ./api:/usr/src/api
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:rabbitmq@rabbitmq:5672
      - CELERY_RESULT_BACKEND=amqp://rabbitmq:rabbitmq@rabbitmq:5672
    depends_on:
      - rabbitmq

  worker:
    build: .
<<<<<<< HEAD
    command: celery worker -A  worker.app_worker --loglevel=info
=======
    command: celery worker -A  worker --loglevel=info
>>>>>>> feat/integrate-celery
    volumes:
      - ./worker:/usr/src/worker
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:rabbitmq@rabbitmq:5672
<<<<<<< HEAD
      - CELERY_RESULT_BACKEND=amqp://rabbitmq:rabbitmq@rabbitmq:5672
=======
      - CELERY_RESULT_BACKEND=rpc://rabbitmq:rabbitmq@rabbitmq:5672
>>>>>>> feat/integrate-celery
    depends_on:
      - rabbitmq
  
  rabbitmq:
        image: rabbitmq:3-management-alpine
        command: rabbitmq-server
        ports:
            - "5672:5672"
            - "15672:15672"
        volumes:
            - ./docker/rabbitmq/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
            - ./docker/rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
  
  dashboard:
    build: .
<<<<<<< HEAD
    command:  celery flower -A worker.app_worker --loglevel=info
=======
    command:  celery flower -A worker --loglevel=info
>>>>>>> feat/integrate-celery
    ports:
      - 5556:5555
    environment:
      - CELERY_BROKER_URL=amqp://rabbitmq:rabbitmq@rabbitmq:5672
      - CELERY_RESULT_BACKEND=amqp://rabbitmq:rabbitmq@rabbitmq:5672
    depends_on:
      - worker
